name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: Use node version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run:  yarn install --frozen-lockfile

    - name: Lint
      run:  yarn lint

    - name: Build
      run:  yarn build

    - name: Test
      run:  yarn test

    # - name: Codechecks
    #   run:  yarn codechecks
